elementary/switchboard-plug-sound

- src/Device.vala
- src/PulseAudioManager.vala
- src/TestPopover.vala
> Check if there is a remaining operation before setting the volume

- src/Device.vala
- src/DeviceRow.vala
- src/InputDeviceMonitor.vala
- src/InputPanel.vala
- src/OutputPanel.vala
- src/Plug.vala
- src/PulseAudioManager.vala
- src/TestPopover.vala
Updates FSF address in license headers
> Update fsf address

- src/OutputPanel.vala
> Add Event Sounds switcher to Output Panel

- src/InputPanel.vala
- src/OutputPanel.vala
> Enable clicking on whole row to select device

- src/InputPanel.vala
- src/OutputPanel.vala
> balance slider has_origin = false

- src/Plug.vala
Alterations to get better results when searching for sub settings. See: https://github.com/elementary/applications-menu/pull/133
> Plug search fixes

- vapi/libpulse.vapi
> Update profiles in vapi

- src/OutputPanel.vala
Adding visual alerts to fix #89
> Rework event alerts

- src/InputPanel.vala
- src/OutputPanel.vala
> Fix label casing according to HIG

- vapi/libpulse-ext.vapi
> vapi: Fix binding of PulseAudio.ExtStreamRestoreInfo

- src/OutputPanel.vala
Add volume scale event sound on volume change, similar to _wingpanel-indicator-sound_.
> Add volume scale event sound

- data/sound.appdata.xml.in
- meson.build
https://github.com/elementary/switchboard-plug-sound/compare/2.2.2...master
**Changelog:**
<p>Minor updates:</p>
<ul>
<li>Updated translations</li>
</ul>
> release 2.2.3

- data/sound.appdata.xml.in
For better display in Feedback and AppCenter
> AppData: Add "Settings" to name

- src/Plug.vala
> Fix plug destroyed on navigation

- data/sound.appdata.xml.in
- meson.build
> Release 2.2.6

- src/meson.build
> Meson: actually add GResources

- data/sound.appdata.xml.in
- meson.build
> Release 2.3.0

- src/PulseAudioManager.vala
Same as https://github.com/elementary/wingpanel-indicator-sound/pull/241
> PulseAudioManager: add device form factor icon fallbacks

- src/OutputPanel.vala
- src/TestPopover.vala
While we're here do some Gtk4 prep and cleanup:
> Output: more vertical layout

- src/InputPanel.vala
- src/OutputPanel.vala
Use the actual source of truth for scale sensitivity, not other UI
> Set volume scales sensitive based on device

- src/PulseAudioManager.vala
> Try to fix crash

- src/Plug.vala
And update "Event Sounds" → "Event Alerts" so translators don't get a duplicate string
> Search Results: include missing output items

- src/DeviceRow.vala
- src/InputPanel.vala
- src/OutputPanel.vala
> Fix device removal

- src/Plug.vala
> Make the stack switcher homogeneous

- src/Plug.vala
> Plug: add margin to stack
